---
- name: "golang | Find Go binary"
  shell: "command -v go"
  register: go_path

- name: "golang | Run install commands"
  shell: "{{ go_path.stdout }} install {{ item }}"
  with_items: "{{ go_install }}"
  changed_when: false
  tags:
    - go_install
