---
- name: set default email
  template:
    src: gitconfig-extra.j2
    dest: "~/.gitconfig-extra"
  when: user.email is defined
- name: create user gitconfigs
  community.general.git_config:
    name: 'user.email'
    scope: file
    value: '{{ user.git.configs[item].email }}'
    file: ~/.gitconfig-{{ item }}
  loop: '{{ user.git.configs.keys() }}'
  when: user.git.configs is defined