---
- hosts: all
  vars_files:
    - default.config.yml
  roles:
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: git, tags: ['git'] }
    - { role: editors, tags: ['editors'] }
    - { role: golang, tags: ['golang'] }
  tasks: []